# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
   name: test

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Starting StaticCodeAnalyzer.ps1 in PowerShell 7..."
      Start-Process pwsh -ArgumentList '-File', 'C:\Users\Administrator\Desktop\StaticCodeAnalyzer.ps1' -Wait -NoNewWindow
    displayName: 'Run StaticCodeAnalyzer.ps1 in PowerShell 7'
    verbosePreference: 'continue'